allow for values to be a scope array
geoffreybauduin/ion-range-slider-angularjs pull request #22
Opened 2017-08-24 22:07 UTC by DarrellBailey

I tried to bind an array and it didn't work. This allows for that.

Is there any particular reason it was a one way previously?

2017-08-25 16:44 UTC, geoffreybauduin commented
Do you mind bumping the version in package.json and bower.json?

2017-08-25 16:45 UTC, geoffreybauduin requested changes
Do you mind bumping the version in package.json and bower.json?

2017-09-27 17:35 UTC, DarrellBailey commented
Wow, I am just now seeing this. Sure!

2017-09-27 18:57 UTC, geoffreybauduin approved these changes

2017-09-27 18:57 UTC, merged